name         'fernandoalmeida-errbit'
version      '0.0.1'
source       'https://github.com/fernandoalmeida/puppet-errbit.git'
author       'Fernando Almeida'
license      'Apache License, Version 2.0'
summary      'A Puppet module for installing and configuring Errbit'
description  'A Puppet module for installing and configuring Errbit'
project_page 'https://github.com/fernandoalmeida/puppet-errbit'
